services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.26.x
    container_name: geoserver
    ports:
      - "8080:8080"
    volumes:
      - /home/hugo_diniz/shapefile:/var/local/geoserver/data
    environment:
      - GEOSERVER_ADMIN_PASSWORD=admin123
    restart: unless-stopped

volumes:
  geoserver_data: